# Generated by Django 5.0.3 on 2024-03-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not Assigned', max_length=100)),
                ('priority', models.CharField(default='Low', max_length=100)),
                ('description', models.CharField(default='Coming soon', max_length=500)),
            ],
        ),
    ]
